name: Build Tweak

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Theos Dependencies
        run: brew install ldid xz

      - name: Setup Theos Framework
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          mkdir -p $HOME/theos/sdks
          git clone --depth=1 https://github.com/theos/sdks.git $HOME/theos-sdks
          mv $HOME/theos-sdks/iPhoneOS14.5.sdk $HOME/theos/sdks/
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Compile Dylib
        run: |
          export THEOS=$HOME/theos
          
          # හිස්ව පවතින Makefile එක වෙනුවට නිවැරදිම එක සර්වර් එක ඇතුළේ නිර්මාණය කිරීම
          cat << 'EOF' > Makefile
          THEOS_DEVICE_IP = 127.0.0.1
          TARGET := iphone:clang:latest:14.5
          ARCHS = arm64 arm64e

          include $(THEOS)/makefiles/common.mk

          TWEAK_NAME = CosmosMenu
          CosmosMenu_FILES = main.mm
          CosmosMenu_CFLAGS = -fobjc-arc -std=c++17

          include $(THEOS)/makefiles/tweak.mk
          EOF

          # දැන් බිල්ඩ් එක සාර්ථකව සිදු කිරීම
          make FINALPACKAGE=1
        
      - name: Upload Finished Dylib
        uses: actions/upload-artifact@v4
        with:
          name: CosmosKeyAuth-Dylib
          path: .theos/obj/debug/*.dylib
