name: Build Tweak

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Theos Dependencies
        run: brew install ldid xz

      - name: Setup Theos Framework
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          mkdir -p $HOME/theos/sdks
          git clone --depth=1 https://github.com/theos/sdks.git $HOME/theos-sdks
          mv $HOME/theos-sdks/iPhoneOS14.5.sdk $HOME/theos/sdks/
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Compile Dylib
        run: |
          export THEOS=$HOME/theos
          # වත්මන් ෆෝල්ඩරයේ තියෙන ෆයිල් මොනවාදැයි බලා නිවැරදිවම ලැයිස්තුගත කර Compile කිරීම
          ls -la
          make -f Makefile FINALPACKAGE=1
        
      - name: Upload Finished Dylib
        uses: actions/upload-artifact@v4
        with:
          name: CosmosKeyAuth-Dylib
          path: .theos/obj/debug/*.dylib
